In [1]:
import torch

In [7]:
import numpy as np

In [15]:
y = np.random.randn(3,3,2)
y

array([[[ 0.4275674 , -1.16874296],
        [ 0.44367615, -0.95419733],
        [-1.44666148,  0.65139129]],

       [[-1.05811005, -0.31377467],
        [-1.67720415,  1.71677431],
        [ 0.02538976, -0.07615574]],

       [[ 0.91296876, -0.64174398],
        [ 0.91849982, -0.33127864],
        [-0.3240016 ,  0.35429509]]])

In [9]:
y.dtype

dtype('float64')

In [16]:
y1 = torch.from_numpy(y)
y1

tensor([[[ 0.4276, -1.1687],
         [ 0.4437, -0.9542],
         [-1.4467,  0.6514]],

        [[-1.0581, -0.3138],
         [-1.6772,  1.7168],
         [ 0.0254, -0.0762]],

        [[ 0.9130, -0.6417],
         [ 0.9185, -0.3313],
         [-0.3240,  0.3543]]], dtype=torch.float64)

y = w * x + b

In [50]:
x = np.random.randint(10,100,(6,3))
x

array([[21, 52, 53],
       [63, 90, 91],
       [86, 86, 61],
       [51, 26, 38],
       [53, 59, 43],
       [31, 15, 31]])

In [80]:
# weights initialization
w = np.random.randn(1,3)
w

array([[0.89300741, 1.23549192, 0.46209013]])

In [87]:
# bias initilization
b = np.random.randn(6)
b

array([-0.4974864 ,  1.44977896,  0.81099069,  0.38454017,  0.77582592,
       -2.23183202])

In [88]:
x1 = torch.tensor(x)
w1 = torch.tensor(w, requires_grad=True)
b1 = torch.tensor(b, requires_grad=True)

In [39]:
target = np.random.randint(10,100,6)
target

array([64, 65, 84, 58, 99, 25])

In [47]:
target = torch.from_numpy(target)

In [55]:
target

tensor([64, 65, 84, 58, 99, 25])

In [84]:
def linear_model(x):
  return x.double() @ torch.t(w1) + b1

In [77]:
x1.shape

torch.Size([6, 3])

In [82]:
w1.shape

torch.Size([1, 3])

In [89]:
pred = linear_model(x1)

In [90]:
pred

tensor([[106.9920, 108.9393, 108.3005, 107.8741, 108.2653, 105.2577],
        [209.0065, 210.9537, 210.3149, 209.8885, 210.2798, 207.2721],
        [210.7410, 212.6882, 212.0494, 211.6230, 212.0143, 209.0066],
        [ 94.7281,  96.6754,  96.0366,  95.6101,  96.0014,  92.9938],
        [139.5958, 141.5431, 140.9043, 140.4778, 140.8691, 137.8615],
        [ 60.0429,  61.9902,  61.3514,  60.9249,  61.3162,  58.3086]],
       dtype=torch.float64, grad_fn=<AddBackward0>)

In [45]:
def mse(pred, target):
  diff = pred - target
  return torch.sum(diff*diff) / diff.numel()

In [48]:
mse(pred, target)

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1