In [2]:
import torch

In [3]:
features = torch.randint(10,100,(6,3))

In [4]:
features.float()

tensor([[77., 25., 52.],
        [65., 89., 28.],
        [63., 97., 17.],
        [52., 55., 59.],
        [77., 69., 13.],
        [20., 79., 63.]])

In [5]:
target = torch.randint(40, 60, (6,1))

In [6]:
target

tensor([[59],
        [45],
        [54],
        [58],
        [42],
        [49]])

In [7]:
w = torch.randn(1, 3, requires_grad=True)
w

tensor([[-0.0304,  1.8984,  0.1026]], requires_grad=True)

In [8]:
w1 = w

In [9]:
b = torch.randn(1, requires_grad=True)
b

tensor([-1.0613], requires_grad=True)

In [10]:
b1 = b

In [11]:
def linear_model(x):
  return x.float() @ w1.t() + b1

In [12]:
pred = linear_model(features)

In [13]:
pred.dtype

torch.float32

In [14]:
def mse(predt, tar):
  diff = predt - tar
  return torch.sum(diff*diff)/diff.numel()

In [15]:
loss = mse(pred, target)
loss

tensor(8876.5928, grad_fn=<DivBackward0>)

In [16]:
loss.backward()

In [17]:
w1.grad

tensor([[ 8942.3027, 13458.3770,  5296.9224]])

In [18]:
b1.grad

tensor([161.8680])

In [19]:
lr = 0.0001

In [20]:
w1.data -= w1.grad*lr

In [21]:
b1.data -= b1.grad*lr

In [22]:
mse(linear_model(features), target)

tensor(8084.9702, grad_fn=<DivBackward0>)

In [23]:
for i in range(100):
  preds = linear_model(features)
  loss = mse(preds, target)
  loss.backward()
  with torch.no_grad():
    w1.data -= w1.grad * lr
    b1.data -= b1.grad * lr
    print("w1: ",w1,
          "\nb1: ",b1)
    w1.grad.zero_()
    b1.grad.zero_()

w1:  tensor([[-0.7493,  0.2557, -0.2676]], requires_grad=True) 
b1:  tensor([-1.0766], requires_grad=True)
w1:  tensor([[0.3532, 1.4059, 0.4336]], requires_grad=True) 
b1:  tensor([-1.0588], requires_grad=True)
w1:  tensor([[-0.5850,  0.1229, -0.1391]], requires_grad=True) 
b1:  tensor([-1.0753], requires_grad=True)
w1:  tensor([[0.4427, 1.2232, 0.5108]], requires_grad=True) 
b1:  tensor([-1.0586], requires_grad=True)
w1:  tensor([[-0.4525,  0.0273, -0.0390]], requires_grad=True) 
b1:  tensor([-1.0742], requires_grad=True)
w1:  tensor([[0.5072, 1.0768, 0.5653]], requires_grad=True) 
b1:  tensor([-1.0585], requires_grad=True)
w1:  tensor([[-0.3449, -0.0402,  0.0395]], requires_grad=True) 
b1:  tensor([-1.0732], requires_grad=True)
w1:  tensor([[0.5528, 0.9586, 0.6029]], requires_grad=True) 
b1:  tensor([-1.0585], requires_grad=True)
w1:  tensor([[-0.2570, -0.0865,  0.1016]], requires_grad=True) 
b1:  tensor([-1.0724], requires_grad=True)
w1:  tensor([[0.5840, 0.8624, 0.6280]], requires_

In [24]:
pred2 = linear_model(features)

In [25]:
target

tensor([[59],
        [45],
        [54],
        [58],
        [42],
        [49]])

In [26]:
mse(pred2, target)

tensor(41.6627, grad_fn=<DivBackward0>)

In [27]:
w1 = w.copy_
b1 = b

In [28]:
w

tensor([[0.4036, 0.1913, 0.5158]], requires_grad=True)

In [29]:
inputs = torch.tensor([[73., 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]]
                   )

In [30]:
targets = torch.tensor([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]]
                   )

In [31]:
from torch import nn

In [32]:
!pip install torch.utils

  Preparing metadata (setup.py) ... done
  Created wheel for torch.utils: filename=torch_utils-0.1.2-py3-none-any.whl size=6187 sha256=f3db56bba9b11e4e52f3dc07dde07cba84c5f7ca7ae45936ab85c46204f4938f
  Stored in directory: /root/.cache/pip/wheels/76/08/f0/378d1fe4aac5aa1e21483918d70b7e3428c4faaac0abda4e15
Successfully built torch.utils


In [33]:
from torch.utils.data import TensorDataset, DataLoader

In [34]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56,  70],
         [ 81, 101],
         [119, 133]]))

In [35]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [36]:
model = nn.Linear(3, 2)

In [37]:
model.weight

Parameter containing:
tensor([[ 0.2406,  0.5310, -0.4234],
        [-0.4081,  0.2693, -0.3118]], requires_grad=True)

In [38]:
model.bias

Parameter containing:
tensor([-0.3061, -0.5491], requires_grad=True)

In [39]:
preds = model(inputs)
preds

tensor([[ 34.6280, -25.7001],
        [ 41.2186, -33.9374],
        [ 67.2236, -18.0443],
        [ 31.4000, -42.1272],
        [ 37.6342, -24.6764],
        [ 34.3375, -26.3775],
        [ 40.2642, -34.5186],
        [ 67.0407, -18.7641],
        [ 31.6904, -41.4497],
        [ 36.9703, -24.5801],
        [ 33.6736, -26.2813],
        [ 40.9281, -34.6148],
        [ 68.1780, -17.4631],
        [ 32.0639, -42.2234],
        [ 37.9247, -23.9989]], grad_fn=<AddmmBackward0>)

In [40]:
import torch.nn.functional as F

In [41]:
loss_fn = F.mse_loss

In [42]:
loss_fn(preds, targets)

tensor(8628.1621, grad_fn=<MseLossBackward0>)

In [43]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [52]:
def fit(epochs, model, lossfn, opti):

  for epoch in range(epochs):

    # train with batches of data
    for xb, yb in train_dl:

      # generate predictions
      pred = model(xb)

      # calculate loss
      loss = lossfn(pred, yb.float())

      # compute gradients
      loss.backward()

      # update parameters using gradients
      opti.step()

      # reset gradients to zero
      opti.zero_grad()

    # printing progress
    if (epoch+1)%10 == 0:
      print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item()}")

In [58]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 10.898661613464355
Epoch [20/100], Loss: 4.862102508544922
Epoch [30/100], Loss: 5.847952842712402
Epoch [40/100], Loss: 12.708669662475586
Epoch [50/100], Loss: 9.848760604858398
Epoch [60/100], Loss: 9.503044128417969
Epoch [70/100], Loss: 10.481196403503418
Epoch [80/100], Loss: 8.024871826171875
Epoch [90/100], Loss: 6.464609622955322
Epoch [100/100], Loss: 10.388861656188965


In [64]:
preds = model(inputs)
preds

tensor([[ 57.0967,  70.4530],
        [ 80.2032,  99.0128],
        [122.0512, 136.0134],
        [ 21.8213,  38.5842],
        [ 98.0375, 115.2669],
        [ 55.8128,  69.3455],
        [ 79.7203,  98.8260],
        [122.1630, 136.4664],
        [ 23.1052,  39.6916],
        [ 98.8385, 116.1876],
        [ 56.6138,  70.2662],
        [ 78.9193,  97.9053],
        [122.5341, 136.2002],
        [ 21.0203,  37.6635],
        [ 99.3214, 116.3744]], grad_fn=<AddmmBackward0>)

In [61]:
targets

tensor([[ 56,  70],
        [ 81, 101],
        [119, 133],
        [ 22,  37],
        [103, 119],
        [ 57,  69],
        [ 80, 102],
        [118, 132],
        [ 21,  38],
        [104, 118],
        [ 57,  69],
        [ 82, 100],
        [118, 134],
        [ 20,  38],
        [102, 120]])